---
navs:
  - name: Tutorial
    icon: icon-speedometer
    isOpen: true
    goto: ui.yml
    badge:
      variant: info
      text: NEW
    children:
      - name: Components
        icon: icon-speedometer
        goto: components.yml
        badge:
          variant: info
          text: NEW
